#ifndef DKRV_CONSTANTS_H
#define DKRV_CONSTANTS_H
#define WINDOW_SIZE 800
#define PLAYER_RADIUS 5
#define PLAYER_VELOCITY 100
#define START_INTERVAL 3
#define ROUND_INTERVAL 3
#define TPS 60
#define FPS 60
#define ID_START_GAME -1
#define ID_SHOW_WINNER -2
#define ID_NEXT_ROUND -3
#define ID_NEW_EFFECT -4
#define ID_EFFECT_COLLECTED -5
#define ID_TURN -6
#define ID_DRAWING -7
#define ID_BLOCKED -8
#define ID_SYNCHRONIZE -9
#define TURN_LEFT true
#define TURN_RIGHT false
#define DRAW -1
#define HOLE_TIMER 0.3
#define HOLE_FREQ 180
#define EFFECT_RADIUS 20
#define EFFECT_TIMER 4
#define EFFECT_FREQ 150
#define EFFECT_FAST_SELF 0
#define EFFECT_FAST_OTHERS 1
#define EFFECT_SLOW_SELF 2
#define EFFECT_SLOW_OTHERS 3
#define DRAWING_ENABLED 1
#define DRAWING_DISABLED -1
#define SYNC_POSITION_DIFF 1
#define SYNC_ANGLE_DIFF 0.005
#define SYNC_INTERVAL 0.5
#define BAR_HEIGHT 5.0f
#define BAR_WIDTH 25.0f
#endif //DKRV_CONSTANTS_H